return {
	{ path = 'assets/scripts/scenes/level1.lua' , imagePathComplete = 'textures/levelCompleted/level1Complete.png' , imagePathUncomplete = 'textures/levelUncompleted/level1Uncomplete.png' },
	{ path = 'assets/scripts/scenes/level2.lua' , imagePathComplete = 'textures/levelCompleted/level2Complete.png' , imagePathUncomplete = 'textures/levelUncompleted/level2Uncomplete.png' },
	{ path = 'assets/scripts/scenes/level3.lua' , imagePathComplete = 'textures/levelCompleted/level3Complete.png' , imagePathUncomplete = 'textures/levelUncompleted/level3Uncomplete.png' },
	{ path = 'assets/scripts/scenes/level4.lua' , imagePathComplete = 'textures/levelCompleted/level4Complete.png' , imagePathUncomplete = 'textures/levelUncompleted/level4Uncomplete.png' },
	{ path = 'assets/scripts/scenes/level5.lua' , imagePathComplete = 'textures/levelCompleted/level5Complete.png' , imagePathUncomplete = 'textures/levelUncompleted/level5Uncomplete.png' },
	{ path = 'assets/scripts/scenes/level6.lua' , imagePathComplete = 'textures/levelCompleted/level6Complete.png' , imagePathUncomplete = 'textures/levelUncompleted/level6Uncomplete.png' },
	{ path = 'assets/scripts/scenes/level7.lua' , imagePathComplete = 'textures/levelCompleted/level7Complete.png' , imagePathUncomplete = 'textures/levelUncompleted/level7Uncomplete.png' },
	{ path = 'assets/scripts/scenes/level8.lua' , imagePathComplete = 'textures/levelCompleted/level8Complete.png' , imagePathUncomplete = 'textures/levelUncompleted/level8Uncomplete.png' },
	{ path = 'assets/scripts/scenes/level9.lua' , imagePathComplete = 'textures/levelCompleted/level9Complete.png' , imagePathUncomplete = 'textures/levelUncompleted/level9Uncomplete.png' },
	{ path = 'assets/scripts/scenes/level10.lua', imagePathComplete = 'textures/levelCompleted/level10Complete.png', imagePathUncomplete = 'textures/levelUncompleted/level10Uncomplete.png' },
	{ path = 'assets/scripts/scenes/level11.lua', imagePathComplete = 'textures/levelCompleted/level11Complete.png', imagePathUncomplete = 'textures/levelUncompleted/level11Uncomplete.png' },
	{ path = 'assets/scripts/scenes/level12.lua', imagePathComplete = 'textures/levelCompleted/level12Complete.png', imagePathUncomplete = 'textures/levelUncompleted/level12Uncomplete.png' },
	{ path = 'assets/scripts/scenes/level13.lua', imagePathComplete = 'textures/levelCompleted/level13Complete.png', imagePathUncomplete = 'textures/levelUncompleted/level13Uncomplete.png' },
	{ path = 'assets/scripts/scenes/level14.lua', imagePathComplete = 'textures/levelCompleted/level14Complete.png', imagePathUncomplete = 'textures/levelUncompleted/level14Uncomplete.png' },
}