return {
	{ path = 'assets/scripts/scenes/level1.lua' },
	{ path = 'assets/scripts/scenes/level2.lua' },
	{ path = 'assets/scripts/scenes/level3.lua' },
	{ path = 'assets/scripts/scenes/level4.lua' },
	{ path = 'assets/scripts/scenes/level5.lua' },
	{ path = 'assets/scripts/scenes/level6.lua' },
	{ path = 'assets/scripts/scenes/level7.lua' },
	{ path = 'assets/scripts/scenes/level8.lua' },
	{ path = 'assets/scripts/scenes/level9.lua' },
	{ path = 'assets/scripts/scenes/level10.lua' },
	{ path = 'assets/scripts/scenes/level11.lua' },
	{ path = 'assets/scripts/scenes/level12.lua' },
	{ path = 'assets/scripts/scenes/level13.lua' },
	{ path = 'assets/scripts/scenes/level14.lua' },
}