level: level1, stars: 3
level: level2, stars: 3
level: level3, stars: 3
level: level4, stars: 3
level: level5, stars: 3
level: level6, stars: 3
level: level7, stars: 3
level: level8, stars: 3
level: level9, stars: 0
level: level10, stars: 3
level: level11, stars: 0
level: level12, stars: 1
level: level13, stars: 0
